### ISSUE TITLE
Please add a license and consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [ittecture/oh-my-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name `oh-my-zsh-theme` is too generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Please add a license file, some people won't use any code that doesn't have a license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by ittecture** [comment]
Hi @unixorn,

Thanks for your message and the suggestions!

I have added the license file and also renamed a bit the repository.

Thanks,
